INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`, `OXTIMESTAMP`) VALUES
#Group display:
(md5(uuid()),	1,	'theme:flow',	'blFullwidthLayout',	'bool',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'bl_showManufacturerSlider',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sDefaultListDisplayType',	'select',	'infogrid', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blShowListDisplayType',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sStartPageListDisplayType',	'select',	'grid', NOW()),
(md5(uuid()),	1,	'theme:flow',	'aNrofCatArticles',	'arr',	'a:4:{i:0;s:2:\"10\";i:1;s:2:\"20\";i:2;s:2:\"50\";i:3;s:3:\"100\";}', NOW()),
(md5(uuid()),	1,	'theme:flow',	'aNrofCatArticlesInGrid',	'arr',	'a:4:{i:0;s:2:\"12\";i:1;s:2:\"16\";i:2;s:2:\"24\";i:3;s:2:\"32\";}', NOW()),
(md5(uuid()),	1,	'theme:flow',	'iNewBasketItemMessage',	'select',	'2', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blShowFinalStep',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blShowBirthdayFields',	'bool',	'1', NOW()),
#Group logo:
(md5(uuid()),	1,	'theme:flow',	'sLogoFile',	'str',	'logo_oxid.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sLogoWidth',	'str',	'200', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sLogoHeight',	'str',	'38', NOW()),
#Group favicon:
(md5(uuid()),	1,	'theme:flow',	'sFaviconFile',	'str',	'favicon.ico', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon16File',	'str',	'favicon_16x16.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon32File',	'str',	'favicon_32x32.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon48File',	'str',	'favicon_48x48.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon64File',	'str',	'favicon_64x64.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon128File',	'str',	'favicon_128x128.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFavicon512File',	'str',	'favicon_512x512.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFaviconMSTileColor',	'str',	'#D83434', NOW()),
#Group header:
(md5(uuid()),    1,  'theme:flow',   'stickyHeader',     'bool', '1', NOW()),
#Group images:
(md5(uuid()),	1,	'theme:flow',	'sIconsize',	'str',	'87*87', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sThumbnailsize',	'str',	'390*245', NOW()),
(md5(uuid()),	1,	'theme:flow',	'aDetailImageSizes',	'aarr',	'a:12:{s:6:\"oxpic1\";s:7:\"540*340\";s:6:\"oxpic2\";s:7:\"540*340\";s:6:\"oxpic3\";s:7:\"540*340\";s:6:\"oxpic4\";s:7:\"540*340\";s:6:\"oxpic5\";s:7:\"540*340\";s:6:\"oxpic6\";s:7:\"540*340\";s:6:\"oxpic7\";s:7:\"540*340\";s:6:\"oxpic8\";s:7:\"540*340\";s:6:\"oxpic9\";s:7:\"540*340\";s:7:\"oxpic10\";s:7:\"540*340\";s:7:\"oxpic11\";s:7:\"540*340\";s:7:\"oxpic12\";s:7:\"540*340\";}', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sZoomImageSize',	'str',	'665*665', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sCatIconsize',	'str',	'168*100', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sCatPromotionsize',	'str',	'370*107', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sCatThumbnailsize',	'str',	'1140*250', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sManufacturerIconsize',	'str',	'100*100', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blSliderShowImageCaption',	'bool',	'1', NOW()),
#Group background:
(md5(uuid()),	1,	'theme:flow',	'sBackgroundColor',	'str',	'#CCEBF5', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blUseBackground',	'bool',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBackgroundPath',	'str',	'mein_hintergrundbild.jpg', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBackgroundSize',	'select',	'cover', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBackgroundPosHorizontal',	'select',	'center', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBackgroundPosVertical',	'select',	'top', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBackgroundRepeat',	'select',	'no-repeat', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blBackgroundAttachment',	'bool',	'1', NOW()),
#Group features:
(md5(uuid()),	1,	'theme:flow',	'bl_showCompareList',	'bool',	'1', NOW()),
(md5(uuid()),    1,  'theme:flow',   'bl_showPriceAlarm', 'bool', '1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'bl_showWishlist',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'bl_showListmania',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'bl_showVouchers',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'bl_showGiftWrapping',	'bool',	'1', NOW()),
#Group footer:
(md5(uuid()),	1,	'theme:flow',	'blFooterShowHelp',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blFooterShowLinks',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blFooterShowNewsletter',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blFooterShowNewsletterForm',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sFacebookUrl',	'str',	'https://www.facebook.com/oxidesales', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sTwitterUrl',	'str',	'https://twitter.com/OXID_eSales', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sYouTubeUrl',	'str',	'https://www.youtube.com/user/oxidesales', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sBlogUrl',	'str',	'http://blog.oxid-esales.com', NOW()),
#Group contact:
(md5(uuid()),	1,	'theme:flow',	'sGoogleMapsAddr',	'str',	'OXID eSales AG, Bertoldstraße 48, 79098 Freiburg', NOW()),
#Group emails:
(md5(uuid()),	1,	'theme:flow',	'sEmailLogo',	'str',	'logo_email.png', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blEmailsShowProductPictures',	'bool',	'', NOW()),
#Group googleanalytics:
(md5(uuid()),	1,	'theme:flow',	'sGATrackingId',	'str',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blUseGAEcommerceTracking',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blUseGAPageTracker',	'bool',	'1', NOW()),
(md5(uuid()),	1,	'theme:flow',	'blGAAnonymizeIPs',	'bool',	'1', NOW()),
#Group googlets:
(md5(uuid()),	1,	'theme:flow',	'blUseGoogleTS',	'bool',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sGoogleVendorId',	'str',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sPageLanguage',	'str',	'de_DE', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sGoogleShoppingAccountId',	'str',	'', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sShippingDaysOnStock',	'str',	'3', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sShippingDaysNotOnStock',	'str',	'5', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sDeliveryDaysOnStock',	'str',	'6', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sDeliveryDaysNotOnStock',	'str',	'14', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sShoppingLanguage',	'str',	'de', NOW()),
(md5(uuid()),	1,	'theme:flow',	'sShoppingCountry',	'str',	'DE', NOW());

INSERT INTO `oxconfigdisplay` (`OXID`, `OXCFGMODULE`, `OXCFGVARNAME`, `OXGROUPING`, `OXVARCONSTRAINT`, `OXPOS`, `OXTIMESTAMP`) VALUES
#Group display:
(md5(uuid()), 'theme:flow', 'blFullwidthLayout', 'display', '', 1000, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showManufacturerSlider', 'display', '', 1005, NOW()),
(md5(uuid()), 'theme:flow', 'sDefaultListDisplayType', 'display', 'infogrid|line|grid', 1010, NOW()),
(md5(uuid()), 'theme:flow', 'blShowListDisplayType', 'display', '', 1015, NOW()),
(md5(uuid()), 'theme:flow', 'sStartPageListDisplayType', 'display', 'infogrid|line|grid', 1020, NOW()),
(md5(uuid()), 'theme:flow', 'aNrofCatArticles', 'display', '', 1025, NOW()),
(md5(uuid()), 'theme:flow', 'aNrofCatArticlesInGrid', 'display', '', 1030, NOW()),
(md5(uuid()), 'theme:flow', 'iNewBasketItemMessage', 'display', '0|1|2|3', 1035, NOW()),
(md5(uuid()), 'theme:flow', 'blShowFinalStep', 'display', '', 1040, NOW()),
(md5(uuid()), 'theme:flow', 'blShowBirthdayFields', 'display', '', 1045, NOW()),
#Group logo:
(md5(uuid()), 'theme:flow', 'sLogoFile', 'logo', '', 1100, NOW()),
(md5(uuid()), 'theme:flow', 'sLogoWidth', 'logo', '', 1105, NOW()),
(md5(uuid()), 'theme:flow', 'sLogoHeight', 'logo', '', 1110, NOW()),
#Group favicon:
(md5(uuid()), 'theme:flow', 'sFaviconFile', 'favicons', '', 1200, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon16File', 'favicons', '', 1205, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon32File', 'favicons', '', 1210, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon48File', 'favicons', '', 1215, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon64File', 'favicons', '', 1220, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon128File', 'favicons', '', 1225, NOW()),
(md5(uuid()), 'theme:flow', 'sFavicon512File', 'favicons', '', 1230, NOW()),
(md5(uuid()), 'theme:flow', 'sFaviconMSTileColor', 'favicons', '', 1235, NOW()),
#Group header:
(md5(uuid()), 'theme:flow', 'stickyHeader', 'header', '', 1300, NOW()),
#Group images:
(md5(uuid()), 'theme:flow', 'sIconsize', 'images', '', 1400, NOW()),
(md5(uuid()), 'theme:flow', 'sThumbnailsize', 'images', '', 1405, NOW()),
(md5(uuid()), 'theme:flow', 'aDetailImageSizes', 'images', '', 1410, NOW()),
(md5(uuid()), 'theme:flow', 'sZoomImageSize', 'images', '', 1415, NOW()),
(md5(uuid()), 'theme:flow', 'sCatIconsize', 'images', '', 1420, NOW()),
(md5(uuid()), 'theme:flow', 'sCatPromotionsize', 'images', '', 1425, NOW()),
(md5(uuid()), 'theme:flow', 'sCatThumbnailsize', 'images', '', 1430, NOW()),
(md5(uuid()), 'theme:flow', 'sManufacturerIconsize', 'images', '', 1435, NOW()),
(md5(uuid()), 'theme:flow', 'blSliderShowImageCaption', 'images', '', 1440, NOW()),
#Group background:
(md5(uuid()), 'theme:flow', 'sBackgroundColor', 'background', '', 1500, NOW()),
(md5(uuid()), 'theme:flow', 'blUseBackground', 'background', '', 1505, NOW()),
(md5(uuid()), 'theme:flow', 'sBackgroundPath', 'background', '', 1510, NOW()),
(md5(uuid()), 'theme:flow', 'sBackgroundSize', 'background', 'cover|contain|normal', 1515, NOW()),
(md5(uuid()), 'theme:flow', 'sBackgroundPosHorizontal', 'background', 'left|right|center', 1520, NOW()),
(md5(uuid()), 'theme:flow', 'sBackgroundPosVertical', 'background', 'top|bottom|center', 1525, NOW()),
(md5(uuid()), 'theme:flow', 'sBackgroundRepeat', 'background', 'no-repeat|repeat-x|repeat-y|repeat', 1530, NOW()),
(md5(uuid()), 'theme:flow', 'blBackgroundAttachment', 'background', '', 1535, NOW()),
#Group features:
(md5(uuid()), 'theme:flow', 'bl_showCompareList', 'features', '', 1600, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showPriceAlarm', 'features', '', 1605, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showWishlist', 'features', '', 1610, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showListmania', 'features', '', 1615, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showVouchers', 'features', '', 1620, NOW()),
(md5(uuid()), 'theme:flow', 'bl_showGiftWrapping', 'features', '', 1625, NOW()),
#Group footer:
(md5(uuid()), 'theme:flow', 'blFooterShowHelp', 'footer', '', 1700, NOW()),
(md5(uuid()), 'theme:flow', 'blFooterShowLinks', 'footer', '', 1705, NOW()),
(md5(uuid()), 'theme:flow', 'blFooterShowNewsletter', 'footer', '', 1710, NOW()),
(md5(uuid()), 'theme:flow', 'blFooterShowNewsletterForm', 'footer', '', 1715, NOW()),
(md5(uuid()), 'theme:flow', 'sFacebookUrl', 'footer', '', 1720, NOW()),
(md5(uuid()), 'theme:flow', 'sTwitterUrl', 'footer', '', 1725, NOW()),
(md5(uuid()), 'theme:flow', 'sYouTubeUrl', 'footer', '', 1730, NOW()),
(md5(uuid()), 'theme:flow', 'sBlogUrl', 'footer', '', 1735, NOW()),
#Group contact:
(md5(uuid()), 'theme:flow', 'sGoogleMapsAddr', 'contact', '', 1800, NOW()),
#Group email:
(md5(uuid()), 'theme:flow', 'sEmailLogo', 'emails', '', 1900, NOW()),
(md5(uuid()), 'theme:flow', 'blEmailsShowProductPictures', 'emails', '', 1905, NOW()),
#Group googleanalytics:
(md5(uuid()), 'theme:flow', 'sGATrackingId', 'googleanalytics', '', 2000, NOW()),
(md5(uuid()), 'theme:flow', 'blUseGAEcommerceTracking', 'googleanalytics', '', 2005, NOW()),
(md5(uuid()), 'theme:flow', 'blUseGAPageTracker', 'googleanalytics', '', 2010, NOW()),
(md5(uuid()), 'theme:flow', 'blGAAnonymizeIPs', 'googleanalytics', '', 2015, NOW()),
#Group googlets:
(md5(uuid()), 'theme:flow', 'blUseGoogleTS', 'googlets', '', 2100, NOW()),
(md5(uuid()), 'theme:flow', 'sGoogleVendorId', 'googlets', '', 2105, NOW()),
(md5(uuid()), 'theme:flow', 'sPageLanguage', 'googlets', '', 2110, NOW()),
(md5(uuid()), 'theme:flow', 'sGoogleShoppingAccountId', 'googlets', '', 2115, NOW()),
(md5(uuid()), 'theme:flow', 'sShippingDaysOnStock', 'googlets', '', 2120, NOW()),
(md5(uuid()), 'theme:flow', 'sShippingDaysNotOnStock', 'googlets', '', 2125, NOW()),
(md5(uuid()), 'theme:flow', 'sDeliveryDaysOnStock', 'googlets', '', 2130, NOW()),
(md5(uuid()), 'theme:flow', 'sDeliveryDaysNotOnStock', 'googlets', '', 2135, NOW()),
(md5(uuid()), 'theme:flow', 'sShoppingLanguage', 'googlets', '', 2140, NOW()),
(md5(uuid()), 'theme:flow', 'sShoppingCountry', 'googlets', '', 2145, NOW());
