[{assign var="shop"      value=$oEmailView->getShop()}]
[{assign var="oViewConf" value=$oEmailView->getViewConfig()}]

[{block name="email_plain_ordershipped_sendemail"}]
[{oxcontent ident="oxordersendplainemail"}]
[{/block}]

[{block name="email_plain_ordershipped_infoheader"}]
[{oxmultilang ident="ORDER_SHIPPED_TO" suffix="COLON"}]
[{/block}]

[{block name="email_plain_ordershipped_address"}]
[{if $order->oxorder__oxdellname->value}]
    [{$order->oxorder__oxdelcompany nofilter}]
    [{$order->oxorder__oxdelfname nofilter}] [{$order->oxorder__oxdellname nofilter}]
    [{$order->oxorder__oxdelstreet nofilter}] [{$order->oxorder__oxdelstreetnr->value}]
    [{$order->oxorder__oxdelstateid->value}]
    [{$order->oxorder__oxdelzip->value}] [{$order->oxorder__oxdelcity nofilter}]
[{else}]
    [{$order->oxorder__oxbillcompany nofilter}]
    [{$order->oxorder__oxbillfname nofilter}] [{$order->oxorder__oxbilllname nofilter}]
    [{$order->oxorder__oxbillstreet nofilter}] [{$order->oxorder__oxbillstreetnr->value}]
    [{$order->oxorder__oxbillstateid->value}]
    [{$order->oxorder__oxbillzip->value}] [{$order->oxorder__oxbillcity nofilter}]
[{/if}]
[{/block}]

[{block name="email_plain_ordershipped_oxordernr"}]
[{oxmultilang ident="ORDER_NUMBER" suffix="COLON"}] [{$order->oxorder__oxordernr->value}]
[{/block}]

[{block name="email_plain_ordershipped_orderarticles"}]
[{foreach from=$order->getOrderArticles(true) item=oOrderArticle}]
[{$oOrderArticle->oxorderarticles__oxamount->value}] [{$oOrderArticle->oxorderarticles__oxtitle nofilter}] [{$oOrderArticle->oxorderarticles__oxselvariant nofilter}]
[{/foreach}]
[{/block}]

[{block name="email_plain_ordershipped_infofooter"}]
[{oxmultilang ident="YOUR_TEAM" args=$shop->oxshops__oxname nofilter}]
[{/block}]

[{block name="email_plain_ordershipped_shipmenttrackingurl"}]
[{if $order->getShipmentTrackingUrl()}][{oxmultilang ident="SHIPMENT_TRACKING" suffix="COLON"}] [{$order->getShipmentTrackingUrl()}][{/if}]
[{/block}]

[{oxcontent ident="oxemailfooterplain"}]
